services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Mypassword
      MYSQL_DATABASE: musicaPIA
      MYSQL_ROOT_HOST: '%'
      
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    ports:
      - "3306:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: Mypassword
      MYSQL_DATABASE: musicaPIA
volumes:
  mysql_data: