services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Mypassword
      MYSQL_DATABASE: musicaPIA
      MYSQL_ROOT_HOST: '%'
      
    ports:
      - "30278:30278"
    expose:
      - '30278'
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    ports:
      - "30001:5000"
volumes:
  mysql_data: